language: cpp
language: cpp
compiler: gcc
dist: xenial # TODO older versions don't have patchelf in apt
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install patchelf gcc-7

before_script:
  - export COMPILER=g++-7
  - export CXX=${COMPILER}
  - export CC=gcc-7
  - ${CXX} --version
  - mkdir tensorflow
  - cd tensorflow
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.12.0.tar.gz -O libtensorflow.tar.gz
  - tar -xvf libtensorflow.tar.gz
  - cd ..
  - mkdir build
  - mkdir release
  - cd build
  - cmake ../API/Tensorflow/native_libs/src/
  - cd ..

jobs:
  include:
    - script:
      - cd build
      - make
      - cd ../release
      - echo "TODO rewriting?"
      - mkdir src
      - cp -r ../API/Tensorflow/src/ .
      - cp -r ../API/Tensorflow/.luna-package/ .
      - cp -r ../API/Tensorflow/native_libs/ .
      - cp -r ../tensorflow/* native_libs/linux/
      - tar -cvf tensorflow_luna_linux.tar.gz *
      - cd ..
    - stage: Github Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        draft: true
        file: tensorflow_luna_linux.tar.gz
        on:
          tags: true
