language: cpp
language: cpp
compiler: gcc
distr: precise
matrix:
  include:
    - env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test
    # - env: COMPILER=g++-6 BUILD_TYPE=Release
    #   addons: &gcc6
    #     apt:
    #       packages: g++-6
    #       sources:
    #         - ubuntu-toolchain-r-test
addons:
  apt:
    update: true
before_install:
  - sudo apt-get install patchelf

before_script:
  - export CXX=${COMPILER}
  - ${CXX} --version
  - mkdir tensorflow
  - cd tensorflow
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.12.0.tar.gz -O libtensorflow.tar.gz
  - tar -xvf libtensorflow.tar.gz
  - cd ..
  - mkdir build
  - mkdir release
  - cd build
  - cmake ../API/Tensorflow/native_libs/src/
  - cd ..

jobs:
  include:
    - script:
      - cd build
      - make
      - cd ../release
      - echo "TODO rewriting?"
      - mkdir src
      - cp -r ../API/Tensorflow/src/ .
      - cp -r ../API/Tensorflow/.luna-package/ .
      - cp -r ../API/Tensorflow/native_libs/ .
      - cp -r ../tensorflow/* native_libs/linux/
      - tar -cvf tensorflow_luna_linux.tar.gz *
      - cd ..
    - stage: Github Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        draft: true
        file: tensorflow_luna_linux.tar.gz
        on:
          tags: true
