version: 1.0.{build}
image: Visual Studio 2017
environment:
  PATH: C:\Python37-x64;C:\stack;%PATH%
  LTF_REPO_PATH: $(APPVEYOR_BUILD_FOLDER)
  TF_USE_LOCAL_LIBRARY: 1

cache:
- C:\Users\appveyor\AppData\Roaming\stack\
- C:\Users\appveyor\AppData\Local\Programs\stack

build_script:
- cd %APPVEYOR_BUILD_FORLDER%
- mkdir tensorflow
- cd tensorflow
- curl -sS -o libtf.zip https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.12.0.zip
- 7z x libtf.zip -y
- cd ..
- mkdir build
- mkdir release
- mkdir release\native_libs
- mkdir release\native_libs\windows
- cd scripts # download and patch the patcher
- mv Main.hs Main2.hs
- git clone https://github.com/luna/dataframes
- xcopy /E /H /Y "dataframes\scripts\*" .
- mv Main2.hs Main.hs
- cd ..
- cd build
- cmake ..\API\Tensorflow\native_libs\src\
- make
- cd ..
- curl -sS -o stack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip -y -oC:\stack stack.exe
- cd scripts
- stack run

artifacts:
- path: LunaTensorflow-Win-x64.7z
  name: LunaTensorflow-Win-x64

# deploy:
#   release: luna-tensorflow-v$(appveyor_build_version)
#   description: 'Nightly build'
#   provider: GitHub
#   auth_token:
#     secure: <your encrypted token> # your encrypted token from GitHub
#   artifact: LunaTensorflow-Win-x64
#   draft: true
#   prerelease: true
#   on:
#     branch: master                 # release from master branch only
#     APPVEYOR_REPO_TAG: true        # deploy on tag push only
