- echo "Running Linux build"
- export COMPILER=g++-7 # prepare compiler
- export CXX=${COMPILER}
- export CC=gcc-7
- export TF_USE_LOCAL_LIBRARY=1
- "${CXX} --version"
- mkdir tensorflow # download TF dependency, TODO downloading protobufs
- cd tensorflow
- wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.12.0.tar.gz -O libtensorflow.tar.gz
- tar -xvf libtensorflow.tar.gz
- chmod u+w lib/*
- cd ..
- mkdir build # prepare folders
- mkdir release
- mkdir release/native_libs
- mkdir release/native_libs/linux/
- cd scripts/ # download and patch the patching script
- mv Main.hs Main2.hs
- git clone https://github.com/luna/dataframes
- mv dataframes/scripts/* .
- mv Main2.hs Main.hs
- cd ..
- cd build
- cmake ../API/Tensorflow/native_libs/src/
- cd ..
